// <auto-generated />
namespace CoffeeShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CartParopertiesIsDeletedandIsCheckedOut : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CartParopertiesIsDeletedandIsCheckedOut));
        
        string IMigrationMetadata.Id
        {
            get { return "201710091036495_Cart Paroperties IsDeleted and IsCheckedOut"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
